create or replace 
PROCEDURE SP_REFRESH_B2B_METADATA
AS
V_INS_CNT NUMBER;
V_PROCE_NAME    ERROR_LOG.PROCE_NAME%TYPE;
BEGIN
---truncate all tables ---

V_PROCE_NAME := 'SP_REFRESH_B2B_METADATA';

DELETE FROM ERROR_LOG where PROCE_NAME = V_PROCE_NAME and TRUNC(LOG_DATE) < TRUNC(SYSDATE);

SP_ERROR_LOG(1,V_PROCE_NAME,SYSDATE, 'TRUNCATION STARTED');

EXECUTE IMMEDIATE 'TRUNCATE TABLE CATALOGUE_B2B_CANCEL REUSE STORAGE';


--2 CATALOGUE_B2B_CANCEL
SP_ERROR_LOG(2,V_PROCE_NAME,SYSDATE, 'INSERT INTO CATALOGUE_B2B_CANCEL TABLE STARTED');

INSERT INTO CATALOGUE_B2B_CANCEL
select distinct sa.line_num as CATALOGUE_NUMBER , TO_CHAR(TRUNC(sa.date_end),'DD-MM-YYYY') AS B2b_END_DATE, 'YES' B2b_CANCEL,TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SSSS') AS DATA_REFRESH_DATE
from B2B_DBA.supplier_parameters@GRDBTOB2BUAT.WORLD sp,
B2B_DBA.atp_stock_availability@GRDBTOB2BUAT.WORLD sa
where 
sa.supplier_code=sp.supplier_code
and sp.level_of_integration='0'
and sa.availability_type='Current'
and sa.stock_status='IS'
and TRUNC(sa.date_end) > TRUNC(sysdate)
;

V_INS_CNT := SQL%ROWCOUNT;

SP_ERROR_LOG(3,V_PROCE_NAME,SYSDATE, V_INS_CNT ||' Rows inserted into CATALOGUE_B2B_CANCEL');

COMMIT;

EXECUTE IMMEDIATE 'ANALYZE TABLE CATALOGUE_B2B_CANCEL COMPUTE STATISTICS';
SP_ERROR_LOG(4,V_PROCE_NAME,SYSDATE,'SP_REFRESH_B2B_METADATA TABLE CATALOGUE_B2B_CANCEL ANALYZED');


EXCEPTION WHEN OTHERS THEN
 SP_ERROR_LOG(5,V_PROCE_NAME,SYSDATE,'RA_RETURN_MSG = ' ||  'Error encountered. Error Code =>  ' || SQLCODE || '. Error Message =>  '|| SQLERRM|| ' Error Line. '||DBMS_UTILITY.format_error_backtrace()) ;
 
END SP_REFRESH_B2B_METADATA;